# Expressions

In [2]:
purchase_price = 100000
state_tax_rate = 0.075
county_tax_rate = 0.02
city_tax_rate = 0.11
sales_tax_rate = state_tax_rate + county_tax_rate + city_tax_rate
sales_tax = purchase_price * sales_tax_rate

In [3]:
p = 100000
r = 0.10
n = 5
simple_interest = p*n*r

In [15]:

amount = p*(1+r)**n

161051.0

In [25]:

rate_double = ((2**(1/5)) -1) * 100

14.869835499703509

In [20]:
 initial = 2766000; final = 2814000

In [21]:
growth_rate = (final/initial) -1
round(growth_rate*100,2)

1.74

In [22]:
rate=( 1.035 * 1.035 * 1.035 * 1.035 * 1.035 * 1.035 * 1.035 * 1.035 *
1.035 * 1.035 - 1)

In [23]:
rate

0.410598760621121

In [24]:

annual_growth_rate = 0.035
ten_year_growth_rate = (1 + annual_growth_rate) ** 10 - 1
ten_year_growth_rate

0.410598760621121

In [25]:
initial = 2.37
changed = 3.38
t = 10
annual_growth_rate = (changed/initial) ** (1/t) - 1
annual_growth_rate

0.03613617208346853

In [26]:
abs(-12)

12

In [27]:
max(2, 2 + 3, 4)

5

In [28]:

import math
import operator
math.sqrt(operator.add(4, 5))

3.0

In [29]:
florida = 2.72
iowa = 16.25
100*abs(florida-iowa)/((florida+iowa)/2)

142.6462836056932

In [30]:
import math
import operator
math.sqrt(operator.add(4, 5))

3.0

In [31]:

math.log 

SyntaxError: invalid syntax (<ipython-input-31-3b27f970b879>, line 2)

In [32]:
math.log(16, 2)

4.0

In [33]:
math.log(16)/math.log(2)

4.0

In [160]:

type(abs)

builtin_function_or_method

In [34]:
.0000000000000000000000008709079

8.709079e-25

In [35]:
-12345678900000000000.0

-1.23456789e+19

In [57]:
"loud".upper()

'LOUD'

In [58]:
'loud'.upper()

'LOUD'

In [59]:
'hitchhiker'.replace('hi', 'ma')

'matchmaker'

In [60]:
s = "train"
t = s.replace('t', 'ing')
u = t.replace('in', 'de')
u

'degrade'

In [164]:

3 > 1 + 1

True

In [62]:


"Dog" > "Catastrophe" > "Cat"

True

In [53]:

"This won't work with a single-quoted string!"

"This won't work with a single-quoted string!"

In [56]:

"That's " + str(1 + 1) + ' ' + str(True)

"That's 2 True"

In [61]:


x = 12
y = 5
min(x, y) <= (x+y)/2 <= max(x, y)

True

In [37]:
import numpy as np

In [44]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
type(data2)

list

In [45]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:

baseline_high = 14.48
highs = [baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684]
highs

[13.6, 14.387, 14.585, 15.164]

In [47]:
highs_array= np.array(highs)
highs_array

array([13.6  , 14.387, 14.585, 15.164])

In [48]:

baseline_high = 14.48
highs = (baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684)
highs

(13.6, 14.387, 14.585, 15.164)

In [49]:
type(highs)

tuple

In [50]:
sum(highs)/len(highs)

14.434000000000001

In [51]:
highs_array = np.array(highs)
highs_array

array([13.6  , 14.387, 14.585, 15.164])

In [55]:

baseline_high = 14.48
highs = [baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684]
highs

[13.6, 14.387, 14.585, 15.164]

In [58]:
import numpy as np
highs_array = np.array(highs)
highs_array

array([13.6  , 14.387, 14.585, 15.164])

In [59]:
highs_array/len(highs)

array([3.4    , 3.59675, 3.64625, 3.791  ])

In [60]:
sum(highs)/len(highs)

14.434000000000001

In [61]:

english_parts_of_speech2 = ("noun", "pronoun", "verb","adverb", "adjective", "conjunction", "preposition","interjection")
english_parts_of_speech2_array = np.array(english_parts_of_speech2)

In [62]:

L = ["noun", "pronoun", "verb","adverb", "adjective", "conjunction", "preposition","interjection"]
english_parts_of_speech = np.array(L)
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'], dtype='<U12')

In [64]:
type(highs)

list

In [65]:

(9/5) * highs_array + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

In [66]:

highs_array
highs_array.size

4

In [67]:
highs_array.mean()

14.434000000000001

In [68]:
highs = highs_array
highs.sum()


57.736000000000004

In [70]:
import numpy as np
np.diff(highs_array)

array([0.787, 0.198, 0.579])

In [71]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [72]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [73]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [74]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

In [75]:
baseline_low = 3.00
lows = (baseline_low - 0.872, baseline_low - 0.629,baseline_low - 0.126, baseline_low + 0.728)
lows

(2.128, 2.371, 2.874, 3.7279999999999998)

In [76]:
lows = np.array(lows)
lows

array([2.128, 2.371, 2.874, 3.728])

In [77]:
highs-lows

array([11.472, 12.016, 11.711, 11.436])

In [80]:

highs - lows

array([11.472, 12.016, 11.711, 11.436])

In [81]:

positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [24]:
positive_terms = 1 / positive_term_denominators
negative_terms = 1 / (positive_term_denominators + 2)
4 * ( sum(positive_terms) - sum(negative_terms) )

3.1413926535917955

In [25]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

In [26]:
2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

3.1415910827951143

In [82]:
def double(x):
    """ Double x """
    return 2*x

In [83]:
double(17)

34

In [84]:
any_name = 42
double(any_name)

84

In [85]:
arr = np.array([3, 4, 5])
arr

array([3, 4, 5])

In [86]:
def percent(x, total):
    
    return round((x/total)*100, 2)

In [87]:
def percents(counts):
    total = counts.sum()
    return np.round((counts/total)*100, 2)

In [89]:
x = (7, 10, 4)
some_array = np.array(x)
percents(some_array)

array([33.33, 47.62, 19.05])

In [93]:
def biggest_difference(array_x):
   
    diffs = np.diff(array_x)
    absolute_diffs = abs(diffs)
    return max(absolute_diffs)

In [94]:
nums = (2, 4, 5, 6, 4, -1, 1)
some_numbers = np.array(nums)

In [96]:
some_numbers = np.array([2, 4, 5, 6, 4, -1, 1])

In [97]:
big_diff = biggest_difference(some_numbers)
print("The biggest difference is", big_diff)

The biggest difference is 5


In [98]:
diffs = np.diff(some_numbers)

In [99]:
diffs

array([ 2,  1,  1, -2, -5,  2])

In [100]:
absolute_diffs = abs(diffs)

In [101]:
absolute_diffs

array([2, 1, 1, 2, 5, 2])

In [103]:
def percents(counts, decimal_places):
    total = counts.sum()
    return np.round((counts/total)*100, decimal_places)
    

In [104]:
def percents(counts, decimal_places=2):
    total = counts.sum()
    return np.round((counts/total)*100, decimal_places)

In [105]:
parts = np.array([2, 1, 4])

In [108]:
print("Rounded to 1 decimal place: ", percents(parts, 1))
print("Rounded to 2 decimal places:", percents(parts, 2))
print("Rounded to 3 decimal places:", percents(parts, 3))

Rounded to 1 decimal place:  [28.6 14.3 57.1]
Rounded to 2 decimal places: [28.57 14.29 57.14]
Rounded to 3 decimal places: [28.571 14.286 57.143]


In [109]:
print("Rounded to the default number of decimal places:",percents(parts))

Rounded to the default number of decimal places: [28.57 14.29 57.14]


In [112]:
def cut_off_at_100(x):
    """The smaller of x and 100"""
    return min(x, 100)
cut_off_at_100(17)

17

In [113]:
cut_off_at_100(117)

100

In [114]:
# input two matrices 
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 

In [115]:
mat1

([1, 6, 5], [3, 4, 8], [2, 12, 3])

In [116]:
# This will return dot product 
result = np.dot(mat1,mat2) 
# print resulted matrix 
print(result) 


[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [117]:
mat1 = ([1,2,3],[1,1,1])

In [118]:
mat1

([1, 2, 3], [1, 1, 1])

In [119]:
mat2 = ([1,1],[1,1], [1,1])  

In [120]:
result = np.dot(mat1,mat2)
result

array([[6, 6],
       [3, 3]])

In [121]:
sum(result)

array([9, 9])

In [123]:
np.cumsum(result)

array([ 6, 12, 15, 18], dtype=int32)