In [3]:
import numpy as np

In [1]:
abs(-3)

3

In [5]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [6]:
a = np.array([1, 4, 5, 8], int)
a

array([1, 4, 5, 8])

In [8]:
 type(a[2])

numpy.int32

In [9]:
a[:2]

array([1, 4])

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
a[:,2]

array([3., 6.])

In [12]:
a[1,:]

array([4., 5., 6.])

In [16]:
a[-1,:]

array([4., 5., 6.])

In [18]:
a[:,-2]

array([2., 5.])

In [20]:
a[:,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
a[:1,:]

array([[1., 2., 3.]])

In [23]:
a[:2,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
a[:2,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [26]:
a[:2,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
a[:1,:]

array([[1., 2., 3.]])

In [28]:
a[:3,:]

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [29]:
a[:2,:1]

array([[1.],
       [4.]])

In [30]:
a[:2,:2]

array([[1., 2.],
       [4., 5.]])

In [31]:
a[:2,:-1]

array([[1., 2.],
       [4., 5.]])

In [32]:
a[:2,:-2]

array([[1.],
       [4.]])

In [33]:
a[-1:,-2:]

array([[8., 9.]])

In [34]:
a.shape

(3, 3)

In [35]:
a.dtype

dtype('float64')

In [37]:
len(a)

3

In [39]:

2 in a 

True

In [41]:
0 in a

False

In [42]:

a = np.array(range(10), float) 
a 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
a = a.reshape((5, 2))

In [44]:
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [46]:

a.shape

(5, 2)

In [49]:
a = np.array([1, 2, 3], float)
b = a
c = a.copy()   
a[0] = 0 

In [50]:
b

array([0., 2., 3.])

In [51]:

c

array([1., 2., 3.])

In [ ]:
 
a = np.array([1, 2, 3], float) 

In [53]:
a

array([0., 2., 3.])

In [54]:
a.tolist()

[0.0, 2.0, 3.0]

In [55]:
type(a.tolist())

list

In [56]:
type(a)

numpy.ndarray

In [59]:

a = np.array([1, 2, 3], float) 

In [60]:
a 

array([1., 2., 3.])

In [61]:
a.fill(0)
a

array([0., 0., 0.])

In [64]:
a = np.array(range(6), float)
a

array([0., 1., 2., 3., 4., 5.])

In [69]:
b = a.reshape((2, 3)) 

In [ ]:
 a array([[ 0., 1., 2.], [ 3., 4., 5.]]) 

In [71]:
b.transpose() 

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [72]:

a = np.array([[1, 2, 3], [4, 5, 6]], float)
a 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [73]:
a.flatten()

array([1., 2., 3., 4., 5., 6.])

In [74]:

a = np.array([1,2], float) 
b = np.array([3,4,5,6], float) 
c = np.array([7,8,9], float)
np.concatenate((a, b, c)) 

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [75]:

a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float) 
np.concatenate((a,b))  

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [76]:
np.concatenate((a,b), axis=0) 

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [77]:
np.concatenate((a,b), axis=1) 

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [78]:
a = np.array([1, 2, 3], float) 
a[:,np.newaxis] 

array([[1.],
       [2.],
       [3.]])

In [79]:
a[:,np.newaxis].shape 


(3, 1)

In [89]:
b

array([[5., 6.],
       [7., 8.]])

In [88]:
a[np.newaxis,:] 

array([[1., 2., 3.]])

In [84]:
b[np.newaxis,:].shape 

(1, 2, 2)

In [90]:
np.arange(1, 6, 2, dtype=int)

array([1, 3, 5])

In [91]:

np.ones((2,3), dtype=float) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [92]:
np.zeros(7, dtype=int) 

array([0, 0, 0, 0, 0, 0, 0])

In [93]:
a = np.array([[1, 2, 3], [4, 5, 6]], float) 
np.zeros_like(a) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:

np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
np.eye(4, k=1, dtype=float)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [99]:
np.eye(4, k=0, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [100]:
np.eye(4, k=2, dtype=float)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
a = np.array([1,2,3], float)

In [102]:
b = np.array([5,2,6], float)

In [103]:
a + b 

array([6., 4., 9.])

In [107]:
a - b

array([-4.,  0., -3.])

In [108]:
a * b

array([ 5.,  4., 18.])

In [109]:
b / a

array([5., 1., 2.])

In [110]:
a % b

array([1., 0., 3.])

In [111]:
b**a

array([  5.,   4., 216.])

In [112]:
a = np.array([[1,2], [3,4]], float) 
b = np.array([[2,0], [1,3]], float) 
a * b 

array([[ 2.,  0.],
       [ 3., 12.]])

In [113]:

a = np.array([1,2,3], float) 
b = np.array([4,5], float) 
a + b Traceback (most recent call last)

SyntaxError: invalid syntax (<ipython-input-113-e7a00b9b1cca>, line 4)

In [114]:
a = np.array([[1, 2], [3, 4], [5, 6]], float) 
b = np.array([-1, 3], float) 
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [3]:
import numpy as np
a = np.array([1, 4, 9], float)
a

array([1., 4., 9.])

In [4]:
np.sqrt(a)

array([1., 2., 3.])

In [6]:
a = np.array([1, 4, 5], int) 
for x in a: 
    print(x)

1
4
5


In [7]:
a = np.array([[1, 2], [3, 4], [5, 6]], float) 
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [8]:
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [9]:
for (x, y) in a:
    print(x * y)

2.0
12.0
30.0


In [10]:
a = np.array([2, 4, 3], float) 
a.sum() 

9.0

In [11]:
a.prod() 

24.0

In [12]:
a = np.array([2, 1, 9], float) 
a.mean() 
a.var() 
a.std()

3.559026084010437

In [14]:
a.max()

9.0

In [15]:
a.min()

1.0

In [18]:

a = np.array([2, 1, 9], float) 
a.argmin() 

1

In [ ]:
a.argmax()

In [21]:
a = np.array([[0, 2], [3, -1], [3, 5]], float) 
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [22]:
a.mean(axis=0)  

array([2., 2.])

In [23]:
a.mean(axis=1) 

array([1., 1., 4.])

In [24]:
a.min(axis=1)

array([ 0., -1.,  3.])

In [26]:
a.min(axis=0)

array([ 0., -1.])

In [27]:
a = np.array([6, 2, 5, -1, 0], float)
a

array([ 6.,  2.,  5., -1.,  0.])

In [28]:
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [30]:
a.sort()
a

array([-1.,  0.,  2.,  5.,  6.])

In [31]:
a = np.array([6, 2, 5, -1, 0], float) 
a.clip(0, 5)

array([5., 2., 5., 0., 0.])

In [32]:

a = np.array([1, 1, 4, 5, 5, 5, 7], float) 
np.unique(a)

array([1., 4., 5., 7.])

In [33]:

a = np.array([[1, 2], [3, 4]], float) 
a.diagonal()

array([1., 4.])

In [63]:
a = np.array([1, 3, 0], float) 
b = np.array([0, 3, 2], float) 
a > b

array([ True, False, False])

In [64]:
a == b 

array([False,  True, False])

In [65]:
a <= b

array([False,  True,  True])

In [66]:
c = a > b 
c

array([ True, False, False])

In [68]:

print(np.sum(c==True))

1


In [38]:

a = np.array([1, 3, 0], float) 
a > 2

array([False,  True, False])

In [39]:

c = np.array([ True, False, False], bool) 

In [40]:
any(c)

True

In [46]:
import collections, numpy
collections.Counter(c)

Counter({True: 1, False: 2})

In [49]:
c.count('True')

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [41]:
all(c)

False

In [44]:
import collections, numpy

a = numpy.array([0, 3, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 3, 4])
collections.Counter(a)

Counter({0: 7, 3: 2, 1: 4, 2: 1, 4: 1})

In [48]:
[1, 2, 3, 4, 1, 4, 1].count(1)

3

In [50]:
c = [1, 2, 3, 4, 1, 4, 1]

In [52]:
c.count(4)

2

In [60]:
import numpy as np
#To count the occurences of a value in a numpy array. 
import numpy as np
a=np.array([0,3,4,3,5,4,7])
print(np.sum(a==3))

2


In [69]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

In [70]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
np.dot(b, a)

array([ 6., 11.])

In [71]:
np.dot(a, b)

array([ 3., 13.])

In [72]:
np.outer(a, b)

array([[0., 0.],
       [2., 3.],
       [4., 6.],
       [6., 9.]])

In [73]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float) 
np.linalg.det(a)

-48.00000000000003

In [74]:
vals, vecs = np.linalg.eig(a)

In [75]:
vals

array([ 8.85591316,  1.9391628 , -2.79507597])

In [76]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

In [78]:

b = np.linalg.inv(a)
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [79]:

a = np.array([[1, 3, 4], [5, 2, 3]], float)  
U, s, Vh = np.linalg.svd(a)

In [80]:
U

array([[-0.6113829 , -0.79133492],
       [-0.79133492,  0.6113829 ]])

In [81]:
s

array([7.46791327, 2.86884495])

In [82]:
Vh

array([[-0.61169129, -0.45753324, -0.64536587],
       [ 0.78971838, -0.40129005, -0.46401635],
       [-0.046676  , -0.79349205,  0.60678804]])

In [84]:
np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

In [85]:
np.roots([1, 4, -2, 3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [86]:
np.roots([1,4,4])

array([-2., -2.])

In [87]:
np.poly([-2,-2]) 

array([1., 4., 4.])

In [88]:
np.polyint([1, 1, 1, 1]) 

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

In [89]:

np.polyder([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

array([1.        , 0.99999999, 1.        , 1.        ])

In [90]:
np.polyval([1, -2, 0, 2], 4)

34

In [91]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float) 
np.median(a)

3.0

In [92]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float) 
c = np.corrcoef(a) 
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [93]:
np.random.seed(293423)

In [94]:
np.random.rand(5)

array([0.33677247, 0.52693437, 0.79529578, 0.78867702, 0.02147624])

In [95]:

np.random.rand(2,3)

array([[0.84612516, 0.0704939 , 0.1526965 ],
       [0.77831701, 0.80821151, 0.82198398]])

In [96]:
np.random.rand(6).reshape((2,3))

array([[0.90239653, 0.8385685 , 0.02638565],
       [0.33681448, 0.46480928, 0.61686496]])

In [97]:

np.random.random()

0.43767262538051455

In [98]:
np.random.randint(5, 10)

5

In [99]:
np.random.randint(5, 10)

6

In [100]:
np.random.seed(293423)
np.random.randint(5, 10)

9

In [101]:
np.random.seed(293423)
np.random.randint(5, 10)

9

In [102]:

np.random.poisson(6.0)

5

In [103]:

np.random.normal(1.5, 4.0)

3.2067741436775075

In [104]:

np.random.normal()

-0.5324581382754698

In [105]:

np.random.normal(size=5)

array([ 0.48976147,  0.46881252,  2.27416107, -0.68480213, -1.16325047])

In [118]:

a = np.arange(1,10) 
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.random.shuffle(a)
a

array([4, 5, 8, 2, 6, 3, 7, 1, 9])

In [123]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([9, 8, 0, 2, 5, 3, 7, 1, 4, 6])